ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

CREATE USER GADAFA IDENTIFIED BY gadafa
DEFAULT TABLESPACE USERS;
GRANT RESOURCE,CONNECT TO GADAFA;
ALTER USER GADAFA QUOTA UNLIMITED ON USERS;
ALTER USER GADAFA IDENTIFIED BY gadafa;
--./LDLIB/imp export/export FILE='/home/oracle/exports/gadafa.dmp' LOG='/home/oracle/exports/gadafa.txt' FROMUSER=gadafa TOUSER=gadafa


SET SERVEROUTPUT ON;
SET VERIFY OFF;


CREATE OR REPLACE PROCEDURE INICIO_SESION(USUARIO IN VARCHAR2, CONTRASENA IN VARCHAR2, ESVALIDO OUT NUMBER)
AS
 CURSOR USUARIOS IS SELECT CORREO,PASSWORD
                    FROM USUARIOS;
BEGIN
    FOR CUR IN USUARIOS
        LOOP
            IF (CUR.CORREO = USUARIO AND CUR.PASSWORD = CONTRASENA) THEN
                ESVALIDO:=1;
                EXIT;
            ELSE
                ESVALIDO:=0;
            END IF;    
        END LOOP;
END;


EXECUTE INICIO_SESION('fabian','test',:V);
SELECT :V FROM DUAL;

--PASISES

INSERT INTO PAISES VALUES(1,'COSTA RICA');

--PROVINCIAS
INSERT INTO PROVINCIAS VALUES(1,'SAN JOSE', 1);

--CANTONES
INSERT INTO CANTONES VALUES(1,'CENTRAL', 1);

--CLIENTES
INSERT INTO CLIENTES VALUES(1,'Carlos','Torres','Barrio Mercedes',1,'ctorres@mail.com','90909090','M','19/JAN/1997');
INSERT INTO CLIENTES VALUES(2,'Claudia','Poll','Barrio Chepe',1,'cpoll@mail.com','80808080','F','19/JAN/1997');
INSERT INTO CLIENTES VALUES(3,'Keylor','Navas','Barrio Belen',1,'knavas@mail.com','70707070','M','19/JAN/1997');

CREATE OR REPLACE PROCEDURE LISTAR_CLIENTES(CUR OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN CUR FOR SELECT C.ID_CLIENTE ID,
                C.NOMBRE NOMBRE,
                C.APELLIDO APELLIDO,
                C.DIRECCION DIRECCION,
                B.NOMBRE CANTON,
                C.CORREO CORREO,
                C.TELEFONO TELEFONO,
                C.GENERO GENERO,
                C.FECHA_NACIMIENTO FECHA_NACIMIENTO
                FROM CLIENTES C, CANTONES B
                WHERE C.ID_CANTON=B.ID_CANTON;
END;

--CATEGORIAS
INSERT INTO CATEGORIAS VALUES(1, 'Lacteos');
INSERT INTO CATEGORIAS VALUES(2, 'Carnes Rojas');
INSERT INTO CATEGORIAS VALUES(3, 'Carnes Blancas');
INSERT INTO CATEGORIAS VALUES(4, 'Verduras');
INSERT INTO CATEGORIAS VALUES(5, 'Frutas');

SELECT * FROM CATEGORIAS;

--PRODUCTOS
INSERT INTO PRODUCTOS VALUES(1, 'Chuleta', 2500, 'Kilo de Chuleta Ahumada', 89,2);
INSERT INTO PRODUCTOS VALUES(2, 'Leche', 900, 'Litro de leche', 150,1);
INSERT INTO PRODUCTOS VALUES(3, 'Pechuga Pollo', 1300, 'Pechuga de Pollo', 120,3);
INSERT INTO PRODUCTOS VALUES(4, 'Papa', 900,'Kilo de Papas', 200,4);
INSERT INTO PRODUCTOS VALUES(5, 'Fresa', 1200, 'Canasta de Fresas', 97,5);

SELECT * FROM PRODUCTOS;

CREATE OR REPLACE PROCEDURE LISTAR_PRODUCTOS(CUR OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN CUR FOR SELECT P.ID_PRODUCTO ID,
                P.NOMBRE NOMBRE,
                P.PRECIO_UNIT PRECIO,
                P.DESCRIPCION DESCRIPCION,
                P.CANTIDAD_INV CANTIDAD,
                C.NOMBRE CATEGORIA
                FROM PRODUCTOS P, CATEGORIAS C
                WHERE P.ID_CATEGORIA=C.ID_CATEGORIA;
END;


--USUARIOS

INSERT INTO USUARIOS VALUES(1,'test','Fabian','Bolanos','Dir',1,'fabian',1234,'M','19/JAN/1997','19/APR/2007',100);
INSERT INTO USUARIOS VALUES(2,'test','Daniel','Coto','Dir',1,'daniel',1234,'M','24/JAN/1993','19/APR/2007',100);
INSERT INTO USUARIOS VALUES(3,'test','Gabriel','Duarte','Dir',1,'gabriel',1234,'M','19/JAN/1997','19/APR/2007',100);


CREATE OR REPLACE PROCEDURE LISTAR_USUARIOS(CUR OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN CUR FOR SELECT U.ID_USUARIO ID,
                U.NOMBRE NOMBRE,
                U.APELLIDO APELLIDO,
                U.CORREO CORREO,
                U.TELEFONO TELEFONO,
                U.DIRECCION DIRECCION,
                U.GENERO GENERO,
                U.FECHA_NACIMIENTO FECHA_NACIMIENTO,
                U.FECHA_INGRESO FECHA_INGRESO,
                U.SALARIO SALARIO,
                C.NOMBRE CANTON,
                P.NOMBRE PROVINCIA,
                P.ID_PAIS ID_PAIS 
                FROM USUARIOS U, CANTONES C, PROVINCIAS P
                WHERE U.ID_CANTON=C.ID_CANTON AND C.ID_PROVINCIA = P.ID_PROVINCIA;
END;

CREATE OR REPLACE PROCEDURE LISTAR_USUARIO(VID IN NUMBER, NOMBRE OUT VARCHAR2,APELLIDO OUT VARCHAR2,CORREO OUT VARCHAR2,
                                            CONTRASENA OUT VARCHAR2, TELEFONO OUT NUMBER,DIRECCION OUT VARCHAR2, CANTON OUT VARCHAR2,PROVINCIA OUT VARCHAR2,
                                            GENERO OUT CHAR,FECHA_NACIMIENTO OUT DATE,FECHA_INGRESO OUT DATE,
                                            SALARIO OUT NUMBER)
AS
 CURSOR USUARIOS IS SELECT * FROM USUARIOS
                    WHERE ID_USUARIO = VID;
BEGIN
    FOR CUR IN USUARIOS
        LOOP
            NOMBRE := CUR.NOMBRE;
            APELLIDO := CUR.APELLIDO;
            CORREO := CUR.CORREO;
            CONTRASENA := CUR.PASSWORD;
            TELEFONO := CUR.TELEFONO;
            DIRECCION := CUR.DIRECCION;
            CANTON := CUR.ID_CANTON;
            PROVINCIA := CUR.ID_CANTON;
            GENERO := CUR.GENERO;
            FECHA_NACIMIENTO := CUR.FECHA_NACIMIENTO;
            FECHA_INGRESO := CUR.FECHA_INGRESO;
            SALARIO := CUR.SALARIO;
        END LOOP;
END;


CREATE OR REPLACE PROCEDURE ACTUALIZAR_USUARIO(VID IN NUMBER,VNOMBRE IN VARCHAR2,VAPELLIDO IN VARCHAR2,VCORREO IN VARCHAR2,
                                            VCONTRASENA IN VARCHAR2, VTELEFONO IN NUMBER,VDIRECCION IN VARCHAR2,
                                            VGENERO IN CHAR,
                                            VFECHA_NACIMIENTO IN DATE,VFECHA_INGRESO IN DATE, VSALARIO IN NUMBER)
AS

BEGIN
    UPDATE USUARIOS
    SET NOMBRE = VNOMBRE,
    APELLIDO = VAPELLIDO,
    CORREO = VCORREO,
    PASSWORD = VCONTRASENA,
    TELEFONO = VTELEFONO,
    DIRECCION = VDIRECCION,
    GENERO = VGENERO,
    FECHA_NACIMIENTO = VFECHA_NACIMIENTO,
    FECHA_INGRESO = VFECHA_INGRESO,
    SALARIO = VSALARIO
    WHERE ID_USUARIO=VID;
    COMMIT;
END;


commit;